version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  selenium:
    image: seleniarm/standalone-chromium
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: "4gb"


volumes:
  mongo-data:
    driver: local