spring:
  ai:
    openai:
      chat:
        api-key: ${OPENAI_API_KEY}
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: WARN
    de:
      anmimi:
        headlines: DEBUG

de:
  anmimi:
    cors:
      host: "http://localhost:5173"
    headlines:
        matching-words:
          - Politic
          - Europe
          - Technology
          - Business
          - Economy
          - USA
          - Ukraine
          - Russia